package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 30 12:35:44 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblExpoSetupImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ExpoSchId,
        ExpoSetupId,
        FDate,
        TDate,
        NoOfDays,
        ExpoSetupVenue,
        TotalHalls,
        STime,
        ETime,
        ExpoSetupArea,
        AreaRate,
        MinExhibitors,
        MaxExhibitors,
        MinStalls,
        MaxStalls,
        MinB2b,
        MaxB2b,
        MinLocalDeleg,
        MaxLocalDeleg,
        MinIntlDeleg,
        MaxIntlDeleg,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        FB2b,
        FExhibitors,
        FIntlDeleg,
        FLocalDeleg,
        FStalls,
        Status,
        Remarks,
        BusLeads,
        FLeads,
        ArrCitFarmer,
        ArrGovFarmer,
        ArrManFarmer,
        ArrVegFarmer,
        DaysExhFarmer,
        DinnerAmount,
        DinnerPerson,
        ExhFarmerMealAmount,
        Fabrication,
        HotelRateExhFarmer,
        MiscProtocol,
        SocialMedia,
        StallFruitVeg,
        TotExhFarmer,
        VipGuestAccomAmount,
        TblExpoHalls,
        TblExhibitors,
        TblExpoIntlDeleg,
        TblExpoSch,
        TblIntlDelegAppM;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXPOSCHID = AttributesEnum.ExpoSchId.index();
    public static final int EXPOSETUPID = AttributesEnum.ExpoSetupId.index();
    public static final int FDATE = AttributesEnum.FDate.index();
    public static final int TDATE = AttributesEnum.TDate.index();
    public static final int NOOFDAYS = AttributesEnum.NoOfDays.index();
    public static final int EXPOSETUPVENUE = AttributesEnum.ExpoSetupVenue.index();
    public static final int TOTALHALLS = AttributesEnum.TotalHalls.index();
    public static final int STIME = AttributesEnum.STime.index();
    public static final int ETIME = AttributesEnum.ETime.index();
    public static final int EXPOSETUPAREA = AttributesEnum.ExpoSetupArea.index();
    public static final int AREARATE = AttributesEnum.AreaRate.index();
    public static final int MINEXHIBITORS = AttributesEnum.MinExhibitors.index();
    public static final int MAXEXHIBITORS = AttributesEnum.MaxExhibitors.index();
    public static final int MINSTALLS = AttributesEnum.MinStalls.index();
    public static final int MAXSTALLS = AttributesEnum.MaxStalls.index();
    public static final int MINB2B = AttributesEnum.MinB2b.index();
    public static final int MAXB2B = AttributesEnum.MaxB2b.index();
    public static final int MINLOCALDELEG = AttributesEnum.MinLocalDeleg.index();
    public static final int MAXLOCALDELEG = AttributesEnum.MaxLocalDeleg.index();
    public static final int MININTLDELEG = AttributesEnum.MinIntlDeleg.index();
    public static final int MAXINTLDELEG = AttributesEnum.MaxIntlDeleg.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int FB2B = AttributesEnum.FB2b.index();
    public static final int FEXHIBITORS = AttributesEnum.FExhibitors.index();
    public static final int FINTLDELEG = AttributesEnum.FIntlDeleg.index();
    public static final int FLOCALDELEG = AttributesEnum.FLocalDeleg.index();
    public static final int FSTALLS = AttributesEnum.FStalls.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int BUSLEADS = AttributesEnum.BusLeads.index();
    public static final int FLEADS = AttributesEnum.FLeads.index();
    public static final int ARRCITFARMER = AttributesEnum.ArrCitFarmer.index();
    public static final int ARRGOVFARMER = AttributesEnum.ArrGovFarmer.index();
    public static final int ARRMANFARMER = AttributesEnum.ArrManFarmer.index();
    public static final int ARRVEGFARMER = AttributesEnum.ArrVegFarmer.index();
    public static final int DAYSEXHFARMER = AttributesEnum.DaysExhFarmer.index();
    public static final int DINNERAMOUNT = AttributesEnum.DinnerAmount.index();
    public static final int DINNERPERSON = AttributesEnum.DinnerPerson.index();
    public static final int EXHFARMERMEALAMOUNT = AttributesEnum.ExhFarmerMealAmount.index();
    public static final int FABRICATION = AttributesEnum.Fabrication.index();
    public static final int HOTELRATEEXHFARMER = AttributesEnum.HotelRateExhFarmer.index();
    public static final int MISCPROTOCOL = AttributesEnum.MiscProtocol.index();
    public static final int SOCIALMEDIA = AttributesEnum.SocialMedia.index();
    public static final int STALLFRUITVEG = AttributesEnum.StallFruitVeg.index();
    public static final int TOTEXHFARMER = AttributesEnum.TotExhFarmer.index();
    public static final int VIPGUESTACCOMAMOUNT = AttributesEnum.VipGuestAccomAmount.index();
    public static final int TBLEXPOHALLS = AttributesEnum.TblExpoHalls.index();
    public static final int TBLEXHIBITORS = AttributesEnum.TblExhibitors.index();
    public static final int TBLEXPOINTLDELEG = AttributesEnum.TblExpoIntlDeleg.index();
    public static final int TBLEXPOSCH = AttributesEnum.TblExpoSch.index();
    public static final int TBLINTLDELEGAPPM = AttributesEnum.TblIntlDelegAppM.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblExpoSetupImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblExpoSetup");
    }


    /**
     * Gets the attribute value for ExpoSchId, using the alias name ExpoSchId.
     * @return the value of ExpoSchId
     */
    public Number getExpoSchId() {
        return (Number) getAttributeInternal(EXPOSCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpoSchId.
     * @param value value to set the ExpoSchId
     */
    public void setExpoSchId(Number value) {
        setAttributeInternal(EXPOSCHID, value);
    }

    /**
     * Gets the attribute value for ExpoSetupId, using the alias name ExpoSetupId.
     * @return the value of ExpoSetupId
     */
    public Number getExpoSetupId() {
        return (Number) getAttributeInternal(EXPOSETUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpoSetupId.
     * @param value value to set the ExpoSetupId
     */
    public void setExpoSetupId(Number value) {
        setAttributeInternal(EXPOSETUPID, value);
    }

    /**
     * Gets the attribute value for FDate, using the alias name FDate.
     * @return the value of FDate
     */
    public Timestamp getFDate() {
        return (Timestamp) getAttributeInternal(FDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FDate.
     * @param value value to set the FDate
     */
    public void setFDate(Timestamp value) {
        setAttributeInternal(FDATE, value);
    }

    /**
     * Gets the attribute value for TDate, using the alias name TDate.
     * @return the value of TDate
     */
    public Timestamp getTDate() {
        return (Timestamp) getAttributeInternal(TDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TDate.
     * @param value value to set the TDate
     */
    public void setTDate(Timestamp value) {
        setAttributeInternal(TDATE, value);
    }

    /**
     * Gets the attribute value for NoOfDays, using the alias name NoOfDays.
     * @return the value of NoOfDays
     */
    public Number getNoOfDays() {
        return (Number) getAttributeInternal(NOOFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfDays.
     * @param value value to set the NoOfDays
     */
    public void setNoOfDays(Number value) {
        setAttributeInternal(NOOFDAYS, value);
    }

    /**
     * Gets the attribute value for ExpoSetupVenue, using the alias name ExpoSetupVenue.
     * @return the value of ExpoSetupVenue
     */
    public String getExpoSetupVenue() {
        return (String) getAttributeInternal(EXPOSETUPVENUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpoSetupVenue.
     * @param value value to set the ExpoSetupVenue
     */
    public void setExpoSetupVenue(String value) {
        setAttributeInternal(EXPOSETUPVENUE, value);
    }

    /**
     * Gets the attribute value for TotalHalls, using the alias name TotalHalls.
     * @return the value of TotalHalls
     */
    public Number getTotalHalls() {
        return (Number) getAttributeInternal(TOTALHALLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalHalls.
     * @param value value to set the TotalHalls
     */
    public void setTotalHalls(Number value) {
        setAttributeInternal(TOTALHALLS, value);
    }

    /**
     * Gets the attribute value for STime, using the alias name STime.
     * @return the value of STime
     */
    public Timestamp getSTime() {
        return (Timestamp) getAttributeInternal(STIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for STime.
     * @param value value to set the STime
     */
    public void setSTime(Timestamp value) {
        setAttributeInternal(STIME, value);
    }

    /**
     * Gets the attribute value for ETime, using the alias name ETime.
     * @return the value of ETime
     */
    public Timestamp getETime() {
        return (Timestamp) getAttributeInternal(ETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ETime.
     * @param value value to set the ETime
     */
    public void setETime(Timestamp value) {
        setAttributeInternal(ETIME, value);
    }

    /**
     * Gets the attribute value for ExpoSetupArea, using the alias name ExpoSetupArea.
     * @return the value of ExpoSetupArea
     */
    public Number getExpoSetupArea() {
        return (Number) getAttributeInternal(EXPOSETUPAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpoSetupArea.
     * @param value value to set the ExpoSetupArea
     */
    public void setExpoSetupArea(Number value) {
        setAttributeInternal(EXPOSETUPAREA, value);
    }

    /**
     * Gets the attribute value for AreaRate, using the alias name AreaRate.
     * @return the value of AreaRate
     */
    public Number getAreaRate() {
        return (Number) getAttributeInternal(AREARATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AreaRate.
     * @param value value to set the AreaRate
     */
    public void setAreaRate(Number value) {
        setAttributeInternal(AREARATE, value);
    }

    /**
     * Gets the attribute value for MinExhibitors, using the alias name MinExhibitors.
     * @return the value of MinExhibitors
     */
    public Number getMinExhibitors() {
        return (Number) getAttributeInternal(MINEXHIBITORS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinExhibitors.
     * @param value value to set the MinExhibitors
     */
    public void setMinExhibitors(Number value) {
        setAttributeInternal(MINEXHIBITORS, value);
    }

    /**
     * Gets the attribute value for MaxExhibitors, using the alias name MaxExhibitors.
     * @return the value of MaxExhibitors
     */
    public Number getMaxExhibitors() {
        return (Number) getAttributeInternal(MAXEXHIBITORS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxExhibitors.
     * @param value value to set the MaxExhibitors
     */
    public void setMaxExhibitors(Number value) {
        setAttributeInternal(MAXEXHIBITORS, value);
    }

    /**
     * Gets the attribute value for MinStalls, using the alias name MinStalls.
     * @return the value of MinStalls
     */
    public Number getMinStalls() {
        return (Number) getAttributeInternal(MINSTALLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinStalls.
     * @param value value to set the MinStalls
     */
    public void setMinStalls(Number value) {
        setAttributeInternal(MINSTALLS, value);
    }

    /**
     * Gets the attribute value for MaxStalls, using the alias name MaxStalls.
     * @return the value of MaxStalls
     */
    public Number getMaxStalls() {
        return (Number) getAttributeInternal(MAXSTALLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxStalls.
     * @param value value to set the MaxStalls
     */
    public void setMaxStalls(Number value) {
        setAttributeInternal(MAXSTALLS, value);
    }

    /**
     * Gets the attribute value for MinB2b, using the alias name MinB2b.
     * @return the value of MinB2b
     */
    public Number getMinB2b() {
        return (Number) getAttributeInternal(MINB2B);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinB2b.
     * @param value value to set the MinB2b
     */
    public void setMinB2b(Number value) {
        setAttributeInternal(MINB2B, value);
    }

    /**
     * Gets the attribute value for MaxB2b, using the alias name MaxB2b.
     * @return the value of MaxB2b
     */
    public Number getMaxB2b() {
        return (Number) getAttributeInternal(MAXB2B);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxB2b.
     * @param value value to set the MaxB2b
     */
    public void setMaxB2b(Number value) {
        setAttributeInternal(MAXB2B, value);
    }

    /**
     * Gets the attribute value for MinLocalDeleg, using the alias name MinLocalDeleg.
     * @return the value of MinLocalDeleg
     */
    public Number getMinLocalDeleg() {
        return (Number) getAttributeInternal(MINLOCALDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinLocalDeleg.
     * @param value value to set the MinLocalDeleg
     */
    public void setMinLocalDeleg(Number value) {
        setAttributeInternal(MINLOCALDELEG, value);
    }

    /**
     * Gets the attribute value for MaxLocalDeleg, using the alias name MaxLocalDeleg.
     * @return the value of MaxLocalDeleg
     */
    public Number getMaxLocalDeleg() {
        return (Number) getAttributeInternal(MAXLOCALDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxLocalDeleg.
     * @param value value to set the MaxLocalDeleg
     */
    public void setMaxLocalDeleg(Number value) {
        setAttributeInternal(MAXLOCALDELEG, value);
    }

    /**
     * Gets the attribute value for MinIntlDeleg, using the alias name MinIntlDeleg.
     * @return the value of MinIntlDeleg
     */
    public Number getMinIntlDeleg() {
        return (Number) getAttributeInternal(MININTLDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinIntlDeleg.
     * @param value value to set the MinIntlDeleg
     */
    public void setMinIntlDeleg(Number value) {
        setAttributeInternal(MININTLDELEG, value);
    }

    /**
     * Gets the attribute value for MaxIntlDeleg, using the alias name MaxIntlDeleg.
     * @return the value of MaxIntlDeleg
     */
    public Number getMaxIntlDeleg() {
        return (Number) getAttributeInternal(MAXINTLDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxIntlDeleg.
     * @param value value to set the MaxIntlDeleg
     */
    public void setMaxIntlDeleg(Number value) {
        setAttributeInternal(MAXINTLDELEG, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for FB2b, using the alias name FB2b.
     * @return the value of FB2b
     */
    public Number getFB2b() {
        return (Number) getAttributeInternal(FB2B);
    }

    /**
     * Sets <code>value</code> as the attribute value for FB2b.
     * @param value value to set the FB2b
     */
    public void setFB2b(Number value) {
        setAttributeInternal(FB2B, value);
    }

    /**
     * Gets the attribute value for FExhibitors, using the alias name FExhibitors.
     * @return the value of FExhibitors
     */
    public Number getFExhibitors() {
        return (Number) getAttributeInternal(FEXHIBITORS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FExhibitors.
     * @param value value to set the FExhibitors
     */
    public void setFExhibitors(Number value) {
        setAttributeInternal(FEXHIBITORS, value);
    }

    /**
     * Gets the attribute value for FIntlDeleg, using the alias name FIntlDeleg.
     * @return the value of FIntlDeleg
     */
    public Number getFIntlDeleg() {
        return (Number) getAttributeInternal(FINTLDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for FIntlDeleg.
     * @param value value to set the FIntlDeleg
     */
    public void setFIntlDeleg(Number value) {
        setAttributeInternal(FINTLDELEG, value);
    }

    /**
     * Gets the attribute value for FLocalDeleg, using the alias name FLocalDeleg.
     * @return the value of FLocalDeleg
     */
    public Number getFLocalDeleg() {
        return (Number) getAttributeInternal(FLOCALDELEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for FLocalDeleg.
     * @param value value to set the FLocalDeleg
     */
    public void setFLocalDeleg(Number value) {
        setAttributeInternal(FLOCALDELEG, value);
    }

    /**
     * Gets the attribute value for FStalls, using the alias name FStalls.
     * @return the value of FStalls
     */
    public Number getFStalls() {
        return (Number) getAttributeInternal(FSTALLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FStalls.
     * @param value value to set the FStalls
     */
    public void setFStalls(Number value) {
        setAttributeInternal(FSTALLS, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for BusLeads, using the alias name BusLeads.
     * @return the value of BusLeads
     */
    public Number getBusLeads() {
        return (Number) getAttributeInternal(BUSLEADS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusLeads.
     * @param value value to set the BusLeads
     */
    public void setBusLeads(Number value) {
        setAttributeInternal(BUSLEADS, value);
    }

    /**
     * Gets the attribute value for FLeads, using the alias name FLeads.
     * @return the value of FLeads
     */
    public Number getFLeads() {
        return (Number) getAttributeInternal(FLEADS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FLeads.
     * @param value value to set the FLeads
     */
    public void setFLeads(Number value) {
        setAttributeInternal(FLEADS, value);
    }

    /**
     * Gets the attribute value for ArrCitFarmer, using the alias name ArrCitFarmer.
     * @return the value of ArrCitFarmer
     */
    public BigDecimal getArrCitFarmer() {
        return (BigDecimal) getAttributeInternal(ARRCITFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArrCitFarmer.
     * @param value value to set the ArrCitFarmer
     */
    public void setArrCitFarmer(BigDecimal value) {
        setAttributeInternal(ARRCITFARMER, value);
    }

    /**
     * Gets the attribute value for ArrGovFarmer, using the alias name ArrGovFarmer.
     * @return the value of ArrGovFarmer
     */
    public BigDecimal getArrGovFarmer() {
        return (BigDecimal) getAttributeInternal(ARRGOVFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArrGovFarmer.
     * @param value value to set the ArrGovFarmer
     */
    public void setArrGovFarmer(BigDecimal value) {
        setAttributeInternal(ARRGOVFARMER, value);
    }

    /**
     * Gets the attribute value for ArrManFarmer, using the alias name ArrManFarmer.
     * @return the value of ArrManFarmer
     */
    public BigDecimal getArrManFarmer() {
        return (BigDecimal) getAttributeInternal(ARRMANFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArrManFarmer.
     * @param value value to set the ArrManFarmer
     */
    public void setArrManFarmer(BigDecimal value) {
        setAttributeInternal(ARRMANFARMER, value);
    }

    /**
     * Gets the attribute value for ArrVegFarmer, using the alias name ArrVegFarmer.
     * @return the value of ArrVegFarmer
     */
    public BigDecimal getArrVegFarmer() {
        return (BigDecimal) getAttributeInternal(ARRVEGFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArrVegFarmer.
     * @param value value to set the ArrVegFarmer
     */
    public void setArrVegFarmer(BigDecimal value) {
        setAttributeInternal(ARRVEGFARMER, value);
    }

    /**
     * Gets the attribute value for DaysExhFarmer, using the alias name DaysExhFarmer.
     * @return the value of DaysExhFarmer
     */
    public BigDecimal getDaysExhFarmer() {
        return (BigDecimal) getAttributeInternal(DAYSEXHFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DaysExhFarmer.
     * @param value value to set the DaysExhFarmer
     */
    public void setDaysExhFarmer(BigDecimal value) {
        setAttributeInternal(DAYSEXHFARMER, value);
    }

    /**
     * Gets the attribute value for DinnerAmount, using the alias name DinnerAmount.
     * @return the value of DinnerAmount
     */
    public BigDecimal getDinnerAmount() {
        return (BigDecimal) getAttributeInternal(DINNERAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DinnerAmount.
     * @param value value to set the DinnerAmount
     */
    public void setDinnerAmount(BigDecimal value) {
        setAttributeInternal(DINNERAMOUNT, value);
    }

    /**
     * Gets the attribute value for DinnerPerson, using the alias name DinnerPerson.
     * @return the value of DinnerPerson
     */
    public BigDecimal getDinnerPerson() {
        return (BigDecimal) getAttributeInternal(DINNERPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for DinnerPerson.
     * @param value value to set the DinnerPerson
     */
    public void setDinnerPerson(BigDecimal value) {
        setAttributeInternal(DINNERPERSON, value);
    }

    /**
     * Gets the attribute value for ExhFarmerMealAmount, using the alias name ExhFarmerMealAmount.
     * @return the value of ExhFarmerMealAmount
     */
    public BigDecimal getExhFarmerMealAmount() {
        return (BigDecimal) getAttributeInternal(EXHFARMERMEALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExhFarmerMealAmount.
     * @param value value to set the ExhFarmerMealAmount
     */
    public void setExhFarmerMealAmount(BigDecimal value) {
        setAttributeInternal(EXHFARMERMEALAMOUNT, value);
    }

    /**
     * Gets the attribute value for Fabrication, using the alias name Fabrication.
     * @return the value of Fabrication
     */
    public BigDecimal getFabrication() {
        return (BigDecimal) getAttributeInternal(FABRICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fabrication.
     * @param value value to set the Fabrication
     */
    public void setFabrication(BigDecimal value) {
        setAttributeInternal(FABRICATION, value);
    }

    /**
     * Gets the attribute value for HotelRateExhFarmer, using the alias name HotelRateExhFarmer.
     * @return the value of HotelRateExhFarmer
     */
    public BigDecimal getHotelRateExhFarmer() {
        return (BigDecimal) getAttributeInternal(HOTELRATEEXHFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for HotelRateExhFarmer.
     * @param value value to set the HotelRateExhFarmer
     */
    public void setHotelRateExhFarmer(BigDecimal value) {
        setAttributeInternal(HOTELRATEEXHFARMER, value);
    }

    /**
     * Gets the attribute value for MiscProtocol, using the alias name MiscProtocol.
     * @return the value of MiscProtocol
     */
    public BigDecimal getMiscProtocol() {
        return (BigDecimal) getAttributeInternal(MISCPROTOCOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for MiscProtocol.
     * @param value value to set the MiscProtocol
     */
    public void setMiscProtocol(BigDecimal value) {
        setAttributeInternal(MISCPROTOCOL, value);
    }

    /**
     * Gets the attribute value for SocialMedia, using the alias name SocialMedia.
     * @return the value of SocialMedia
     */
    public BigDecimal getSocialMedia() {
        return (BigDecimal) getAttributeInternal(SOCIALMEDIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for SocialMedia.
     * @param value value to set the SocialMedia
     */
    public void setSocialMedia(BigDecimal value) {
        setAttributeInternal(SOCIALMEDIA, value);
    }

    /**
     * Gets the attribute value for StallFruitVeg, using the alias name StallFruitVeg.
     * @return the value of StallFruitVeg
     */
    public BigDecimal getStallFruitVeg() {
        return (BigDecimal) getAttributeInternal(STALLFRUITVEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for StallFruitVeg.
     * @param value value to set the StallFruitVeg
     */
    public void setStallFruitVeg(BigDecimal value) {
        setAttributeInternal(STALLFRUITVEG, value);
    }

    /**
     * Gets the attribute value for TotExhFarmer, using the alias name TotExhFarmer.
     * @return the value of TotExhFarmer
     */
    public BigDecimal getTotExhFarmer() {
        return (BigDecimal) getAttributeInternal(TOTEXHFARMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotExhFarmer.
     * @param value value to set the TotExhFarmer
     */
    public void setTotExhFarmer(BigDecimal value) {
        setAttributeInternal(TOTEXHFARMER, value);
    }

    /**
     * Gets the attribute value for VipGuestAccomAmount, using the alias name VipGuestAccomAmount.
     * @return the value of VipGuestAccomAmount
     */
    public BigDecimal getVipGuestAccomAmount() {
        return (BigDecimal) getAttributeInternal(VIPGUESTACCOMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VipGuestAccomAmount.
     * @param value value to set the VipGuestAccomAmount
     */
    public void setVipGuestAccomAmount(BigDecimal value) {
        setAttributeInternal(VIPGUESTACCOMAMOUNT, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblExpoHalls() {
        return (RowIterator) getAttributeInternal(TBLEXPOHALLS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblExhibitors() {
        return (RowIterator) getAttributeInternal(TBLEXHIBITORS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblExpoIntlDeleg() {
        return (RowIterator) getAttributeInternal(TBLEXPOINTLDELEG);
    }

    /**
     * @return the associated entity TblExpoSchImpl.
     */
    public TblExpoSchImpl getTblExpoSch() {
        return (TblExpoSchImpl) getAttributeInternal(TBLEXPOSCH);
    }

    /**
     * Sets <code>value</code> as the associated entity TblExpoSchImpl.
     */
    public void setTblExpoSch(TblExpoSchImpl value) {
        setAttributeInternal(TBLEXPOSCH, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblIntlDelegAppM() {
        return (RowIterator) getAttributeInternal(TBLINTLDELEGAPPM);
    }


    /**
     * @param expoSetupId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number expoSetupId) {
        return new Key(new Object[] { expoSetupId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                 try {
                     loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
                 } catch(Exception ex) {
                     ex.printStackTrace();
                 }
                 
                 if (operation == DML_INSERT) {
                     setCreatedBy(loginId);
                     setUpdatedBy(loginId);
                     } else if(operation == DML_UPDATE) {
                     setUpdatedBy(loginId);
                 }
        super.doDML(operation, e);
    }
}

