package model.EO;

import oracle.jbo.domain.Number;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 31 12:43:07 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFarmerRegCropsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FarmerRegCropsId,
        FarmerRegId,
        CropId,
        AnnualProd,
        YearlySales,
        MainBuyer,
        MainBuyerAddr,
        MainBuyerCity,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        CropTypeId,
        TblCrop,
        TblFarmerReg,
        Map_Farmer_Detail;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FARMERREGCROPSID = AttributesEnum.FarmerRegCropsId.index();
    public static final int FARMERREGID = AttributesEnum.FarmerRegId.index();
    public static final int CROPID = AttributesEnum.CropId.index();
    public static final int ANNUALPROD = AttributesEnum.AnnualProd.index();
    public static final int YEARLYSALES = AttributesEnum.YearlySales.index();
    public static final int MAINBUYER = AttributesEnum.MainBuyer.index();
    public static final int MAINBUYERADDR = AttributesEnum.MainBuyerAddr.index();
    public static final int MAINBUYERCITY = AttributesEnum.MainBuyerCity.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int CROPTYPEID = AttributesEnum.CropTypeId.index();
    public static final int TBLCROP = AttributesEnum.TblCrop.index();
    public static final int TBLFARMERREG = AttributesEnum.TblFarmerReg.index();
    public static final int MAP_FARMER_DETAIL = AttributesEnum.Map_Farmer_Detail.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFarmerRegCropsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFarmerRegCrops");
    }


    /**
     * Gets the attribute value for FarmerRegCropsId, using the alias name FarmerRegCropsId.
     * @return the value of FarmerRegCropsId
     */
    public Number getFarmerRegCropsId() {
        return (Number) getAttributeInternal(FARMERREGCROPSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegCropsId.
     * @param value value to set the FarmerRegCropsId
     */
    public void setFarmerRegCropsId(Number value) {
        setAttributeInternal(FARMERREGCROPSID, value);
    }

    /**
     * Gets the attribute value for FarmerRegId, using the alias name FarmerRegId.
     * @return the value of FarmerRegId
     */
    public Number getFarmerRegId() {
        return (Number) getAttributeInternal(FARMERREGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegId.
     * @param value value to set the FarmerRegId
     */
    public void setFarmerRegId(Number value) {
        setAttributeInternal(FARMERREGID, value);
    }

    /**
     * Gets the attribute value for CropId, using the alias name CropId.
     * @return the value of CropId
     */
    public Number getCropId() {
        return (Number) getAttributeInternal(CROPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CropId.
     * @param value value to set the CropId
     */
    public void setCropId(Number value) {
        setAttributeInternal(CROPID, value);
    }

    /**
     * Gets the attribute value for AnnualProd, using the alias name AnnualProd.
     * @return the value of AnnualProd
     */
    public Number getAnnualProd() {
        return (Number) getAttributeInternal(ANNUALPROD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnnualProd.
     * @param value value to set the AnnualProd
     */
    public void setAnnualProd(Number value) {
        setAttributeInternal(ANNUALPROD, value);
    }

    /**
     * Gets the attribute value for YearlySales, using the alias name YearlySales.
     * @return the value of YearlySales
     */
    public Number getYearlySales() {
        return (Number) getAttributeInternal(YEARLYSALES);
    }

    /**
     * Sets <code>value</code> as the attribute value for YearlySales.
     * @param value value to set the YearlySales
     */
    public void setYearlySales(Number value) {
        setAttributeInternal(YEARLYSALES, value);
    }

    /**
     * Gets the attribute value for MainBuyer, using the alias name MainBuyer.
     * @return the value of MainBuyer
     */
    public String getMainBuyer() {
        return (String) getAttributeInternal(MAINBUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MainBuyer.
     * @param value value to set the MainBuyer
     */
    public void setMainBuyer(String value) {
        setAttributeInternal(MAINBUYER, value);
    }

    /**
     * Gets the attribute value for MainBuyerAddr, using the alias name MainBuyerAddr.
     * @return the value of MainBuyerAddr
     */
    public String getMainBuyerAddr() {
        return (String) getAttributeInternal(MAINBUYERADDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for MainBuyerAddr.
     * @param value value to set the MainBuyerAddr
     */
    public void setMainBuyerAddr(String value) {
        setAttributeInternal(MAINBUYERADDR, value);
    }

    /**
     * Gets the attribute value for MainBuyerCity, using the alias name MainBuyerCity.
     * @return the value of MainBuyerCity
     */
    public String getMainBuyerCity() {
        return (String) getAttributeInternal(MAINBUYERCITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for MainBuyerCity.
     * @param value value to set the MainBuyerCity
     */
    public void setMainBuyerCity(String value) {
        setAttributeInternal(MAINBUYERCITY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for CropTypeId, using the alias name CropTypeId.
     * @return the value of CropTypeId
     */
    public Number getCropTypeId() {
        return (Number) getAttributeInternal(CROPTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CropTypeId.
     * @param value value to set the CropTypeId
     */
    public void setCropTypeId(Number value) {
        setAttributeInternal(CROPTYPEID, value);
    }

    /**
     * @return the associated entity TblCropImpl.
     */
    public TblCropImpl getTblCrop() {
        return (TblCropImpl) getAttributeInternal(TBLCROP);
    }

    /**
     * Sets <code>value</code> as the associated entity TblCropImpl.
     */
    public void setTblCrop(TblCropImpl value) {
        setAttributeInternal(TBLCROP, value);
    }

    /**
     * @return the associated entity TblFarmerRegImpl.
     */
    public TblFarmerRegImpl getTblFarmerReg() {
        return (TblFarmerRegImpl) getAttributeInternal(TBLFARMERREG);
    }

    /**
     * Sets <code>value</code> as the associated entity TblFarmerRegImpl.
     */
    public void setTblFarmerReg(TblFarmerRegImpl value) {
        setAttributeInternal(TBLFARMERREG, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getMap_Farmer_Detail() {
        return (EntityImpl) getAttributeInternal(MAP_FARMER_DETAIL);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMap_Farmer_Detail(EntityImpl value) {
        setAttributeInternal(MAP_FARMER_DETAIL, value);
    }


    /**
     * @param farmerRegCropsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number farmerRegCropsId) {
        return new Key(new Object[] { farmerRegCropsId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

