package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 31 12:33:03 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblFarmerRegImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FarmerRegId,
        Name,
        FatherName,
        Ast,
        Gender,
        ClusterId,
        BeneficiaryId,
        MarStatus,
        Dob,
        Doj,
        Ntn,
        PassNo,
        Cnic,
        DrLicNo,
        Telephone,
        Mobile,
        Email,
        Url,
        PreAddress,
        PerAddress,
        Image,
        FarmerNo,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblClusterAttDetail,
        TblClusterDetail,
        TblBeneficiary,
        TblCluster,
        TblFarmerRegCert,
        TblFarmerRegCrops,
        TblFarmerRegLand,
        TblFarmerRegMem,
        TblFarmerRegOwnership,
        TblGrantApprovalDetail,
        TblGrantAppMaster,
        TblGrantDisburseDetail;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FARMERREGID = AttributesEnum.FarmerRegId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int FATHERNAME = AttributesEnum.FatherName.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int CLUSTERID = AttributesEnum.ClusterId.index();
    public static final int BENEFICIARYID = AttributesEnum.BeneficiaryId.index();
    public static final int MARSTATUS = AttributesEnum.MarStatus.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int DOJ = AttributesEnum.Doj.index();
    public static final int NTN = AttributesEnum.Ntn.index();
    public static final int PASSNO = AttributesEnum.PassNo.index();
    public static final int CNIC = AttributesEnum.Cnic.index();
    public static final int DRLICNO = AttributesEnum.DrLicNo.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int PREADDRESS = AttributesEnum.PreAddress.index();
    public static final int PERADDRESS = AttributesEnum.PerAddress.index();
    public static final int IMAGE = AttributesEnum.Image.index();
    public static final int FARMERNO = AttributesEnum.FarmerNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLCLUSTERATTDETAIL = AttributesEnum.TblClusterAttDetail.index();
    public static final int TBLCLUSTERDETAIL = AttributesEnum.TblClusterDetail.index();
    public static final int TBLBENEFICIARY = AttributesEnum.TblBeneficiary.index();
    public static final int TBLCLUSTER = AttributesEnum.TblCluster.index();
    public static final int TBLFARMERREGCERT = AttributesEnum.TblFarmerRegCert.index();
    public static final int TBLFARMERREGCROPS = AttributesEnum.TblFarmerRegCrops.index();
    public static final int TBLFARMERREGLAND = AttributesEnum.TblFarmerRegLand.index();
    public static final int TBLFARMERREGMEM = AttributesEnum.TblFarmerRegMem.index();
    public static final int TBLFARMERREGOWNERSHIP = AttributesEnum.TblFarmerRegOwnership.index();
    public static final int TBLGRANTAPPROVALDETAIL = AttributesEnum.TblGrantApprovalDetail.index();
    public static final int TBLGRANTAPPMASTER = AttributesEnum.TblGrantAppMaster.index();
    public static final int TBLGRANTDISBURSEDETAIL = AttributesEnum.TblGrantDisburseDetail.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblFarmerRegImpl() {
    }

    /**
     * Gets the attribute value for FarmerRegId, using the alias name FarmerRegId.
     * @return the value of FarmerRegId
     */
    public BigDecimal getFarmerRegId() {
        return (BigDecimal) getAttributeInternal(FARMERREGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegId.
     * @param value value to set the FarmerRegId
     */
    public void setFarmerRegId(BigDecimal value) {
        setAttributeInternal(FARMERREGID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for FatherName, using the alias name FatherName.
     * @return the value of FatherName
     */
    public String getFatherName() {
        return (String) getAttributeInternal(FATHERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FatherName.
     * @param value value to set the FatherName
     */
    public void setFatherName(String value) {
        setAttributeInternal(FATHERNAME, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for ClusterId, using the alias name ClusterId.
     * @return the value of ClusterId
     */
    public BigDecimal getClusterId() {
        return (BigDecimal) getAttributeInternal(CLUSTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClusterId.
     * @param value value to set the ClusterId
     */
    public void setClusterId(BigDecimal value) {
        setAttributeInternal(CLUSTERID, value);
    }

    /**
     * Gets the attribute value for BeneficiaryId, using the alias name BeneficiaryId.
     * @return the value of BeneficiaryId
     */
    public BigDecimal getBeneficiaryId() {
        return (BigDecimal) getAttributeInternal(BENEFICIARYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeneficiaryId.
     * @param value value to set the BeneficiaryId
     */
    public void setBeneficiaryId(BigDecimal value) {
        setAttributeInternal(BENEFICIARYID, value);
    }

    /**
     * Gets the attribute value for MarStatus, using the alias name MarStatus.
     * @return the value of MarStatus
     */
    public String getMarStatus() {
        return (String) getAttributeInternal(MARSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarStatus.
     * @param value value to set the MarStatus
     */
    public void setMarStatus(String value) {
        setAttributeInternal(MARSTATUS, value);
    }

    /**
     * Gets the attribute value for Dob, using the alias name Dob.
     * @return the value of Dob
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dob.
     * @param value value to set the Dob
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for Doj, using the alias name Doj.
     * @return the value of Doj
     */
    public Timestamp getDoj() {
        return (Timestamp) getAttributeInternal(DOJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Doj.
     * @param value value to set the Doj
     */
    public void setDoj(Timestamp value) {
        setAttributeInternal(DOJ, value);
    }

    /**
     * Gets the attribute value for Ntn, using the alias name Ntn.
     * @return the value of Ntn
     */
    public String getNtn() {
        return (String) getAttributeInternal(NTN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ntn.
     * @param value value to set the Ntn
     */
    public void setNtn(String value) {
        setAttributeInternal(NTN, value);
    }

    /**
     * Gets the attribute value for PassNo, using the alias name PassNo.
     * @return the value of PassNo
     */
    public String getPassNo() {
        return (String) getAttributeInternal(PASSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassNo.
     * @param value value to set the PassNo
     */
    public void setPassNo(String value) {
        setAttributeInternal(PASSNO, value);
    }

    /**
     * Gets the attribute value for Cnic, using the alias name Cnic.
     * @return the value of Cnic
     */
    public String getCnic() {
        return (String) getAttributeInternal(CNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cnic.
     * @param value value to set the Cnic
     */
    public void setCnic(String value) {
        setAttributeInternal(CNIC, value);
    }

    /**
     * Gets the attribute value for DrLicNo, using the alias name DrLicNo.
     * @return the value of DrLicNo
     */
    public String getDrLicNo() {
        return (String) getAttributeInternal(DRLICNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrLicNo.
     * @param value value to set the DrLicNo
     */
    public void setDrLicNo(String value) {
        setAttributeInternal(DRLICNO, value);
    }

    /**
     * Gets the attribute value for Telephone, using the alias name Telephone.
     * @return the value of Telephone
     */
    public String getTelephone() {
        return (String) getAttributeInternal(TELEPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Telephone.
     * @param value value to set the Telephone
     */
    public void setTelephone(String value) {
        setAttributeInternal(TELEPHONE, value);
    }

    /**
     * Gets the attribute value for Mobile, using the alias name Mobile.
     * @return the value of Mobile
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mobile.
     * @param value value to set the Mobile
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Url, using the alias name Url.
     * @return the value of Url
     */
    public String getUrl() {
        return (String) getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Url.
     * @param value value to set the Url
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for PreAddress, using the alias name PreAddress.
     * @return the value of PreAddress
     */
    public String getPreAddress() {
        return (String) getAttributeInternal(PREADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreAddress.
     * @param value value to set the PreAddress
     */
    public void setPreAddress(String value) {
        setAttributeInternal(PREADDRESS, value);
    }

    /**
     * Gets the attribute value for PerAddress, using the alias name PerAddress.
     * @return the value of PerAddress
     */
    public String getPerAddress() {
        return (String) getAttributeInternal(PERADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PerAddress.
     * @param value value to set the PerAddress
     */
    public void setPerAddress(String value) {
        setAttributeInternal(PERADDRESS, value);
    }

    /**
     * Gets the attribute value for Image, using the alias name Image.
     * @return the value of Image
     */
    public String getImage() {
        return (String) getAttributeInternal(IMAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Image.
     * @param value value to set the Image
     */
    public void setImage(String value) {
        setAttributeInternal(IMAGE, value);
    }

    /**
     * Gets the attribute value for FarmerNo, using the alias name FarmerNo.
     * @return the value of FarmerNo
     */
    public String getFarmerNo() {
        return (String) getAttributeInternal(FARMERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerNo.
     * @param value value to set the FarmerNo
     */
    public void setFarmerNo(String value) {
        setAttributeInternal(FARMERNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblClusterAttDetail() {
        return (RowIterator) getAttributeInternal(TBLCLUSTERATTDETAIL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblClusterDetail() {
        return (RowIterator) getAttributeInternal(TBLCLUSTERDETAIL);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblBeneficiary() {
        return (EntityImpl) getAttributeInternal(TBLBENEFICIARY);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblBeneficiary(EntityImpl value) {
        setAttributeInternal(TBLBENEFICIARY, value);
    }

    /**
     * @return the associated entity TblClusterImpl.
     */
    public TblClusterImpl getTblCluster() {
        return (TblClusterImpl) getAttributeInternal(TBLCLUSTER);
    }

    /**
     * Sets <code>value</code> as the associated entity TblClusterImpl.
     */
    public void setTblCluster(TblClusterImpl value) {
        setAttributeInternal(TBLCLUSTER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFarmerRegCert() {
        return (RowIterator) getAttributeInternal(TBLFARMERREGCERT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFarmerRegCrops() {
        return (RowIterator) getAttributeInternal(TBLFARMERREGCROPS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFarmerRegLand() {
        return (RowIterator) getAttributeInternal(TBLFARMERREGLAND);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFarmerRegMem() {
        return (RowIterator) getAttributeInternal(TBLFARMERREGMEM);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblFarmerRegOwnership() {
        return (RowIterator) getAttributeInternal(TBLFARMERREGOWNERSHIP);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblGrantApprovalDetail() {
        return (RowIterator) getAttributeInternal(TBLGRANTAPPROVALDETAIL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblGrantAppMaster() {
        return (RowIterator) getAttributeInternal(TBLGRANTAPPMASTER);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblGrantDisburseDetail() {
        return (RowIterator) getAttributeInternal(TBLGRANTDISBURSEDETAIL);
    }

    /**
     * @param farmerRegId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal farmerRegId) {
        return new Key(new Object[] { farmerRegId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblFarmerReg");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        BigDecimal loginId = null;
         try {
             loginId = new BigDecimal((String) ADFContext.getCurrent().getSessionScope().get("sessUID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
         } else {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

