package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 31 12:38:04 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblGrantApprovalDetailImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GrantApprovalDetailId,
        GrantApprovalMasterId,
        FarmerRegId,
        GrantAppMasterId,
        Acre,
        Rate,
        Amount,
        Ast,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        FAcre,
        GrantAmount,
        GrantRateId,
        FAmount,
        GrantStatus,
        RoNumber,
        RoStatus,
        DisburseStatus,
        Remarks,
        TblFarmerReg,
        TblGrantApprovalMaster,
        TblGrantAppMaster,
        TblGrantRate,
        TblGrantApprovalDetailD;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GRANTAPPROVALDETAILID = AttributesEnum.GrantApprovalDetailId.index();
    public static final int GRANTAPPROVALMASTERID = AttributesEnum.GrantApprovalMasterId.index();
    public static final int FARMERREGID = AttributesEnum.FarmerRegId.index();
    public static final int GRANTAPPMASTERID = AttributesEnum.GrantAppMasterId.index();
    public static final int ACRE = AttributesEnum.Acre.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int FACRE = AttributesEnum.FAcre.index();
    public static final int GRANTAMOUNT = AttributesEnum.GrantAmount.index();
    public static final int GRANTRATEID = AttributesEnum.GrantRateId.index();
    public static final int FAMOUNT = AttributesEnum.FAmount.index();
    public static final int GRANTSTATUS = AttributesEnum.GrantStatus.index();
    public static final int RONUMBER = AttributesEnum.RoNumber.index();
    public static final int ROSTATUS = AttributesEnum.RoStatus.index();
    public static final int DISBURSESTATUS = AttributesEnum.DisburseStatus.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int TBLFARMERREG = AttributesEnum.TblFarmerReg.index();
    public static final int TBLGRANTAPPROVALMASTER = AttributesEnum.TblGrantApprovalMaster.index();
    public static final int TBLGRANTAPPMASTER = AttributesEnum.TblGrantAppMaster.index();
    public static final int TBLGRANTRATE = AttributesEnum.TblGrantRate.index();
    public static final int TBLGRANTAPPROVALDETAILD = AttributesEnum.TblGrantApprovalDetailD.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblGrantApprovalDetailImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblGrantApprovalDetail");
    }


    /**
     * Gets the attribute value for GrantApprovalDetailId, using the alias name GrantApprovalDetailId.
     * @return the value of GrantApprovalDetailId
     */
    public BigDecimal getGrantApprovalDetailId() {
        return (BigDecimal) getAttributeInternal(GRANTAPPROVALDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantApprovalDetailId.
     * @param value value to set the GrantApprovalDetailId
     */
    public void setGrantApprovalDetailId(BigDecimal value) {
        setAttributeInternal(GRANTAPPROVALDETAILID, value);
    }

    /**
     * Gets the attribute value for GrantApprovalMasterId, using the alias name GrantApprovalMasterId.
     * @return the value of GrantApprovalMasterId
     */
    public BigDecimal getGrantApprovalMasterId() {
        return (BigDecimal) getAttributeInternal(GRANTAPPROVALMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantApprovalMasterId.
     * @param value value to set the GrantApprovalMasterId
     */
    public void setGrantApprovalMasterId(BigDecimal value) {
        setAttributeInternal(GRANTAPPROVALMASTERID, value);
    }

    /**
     * Gets the attribute value for FarmerRegId, using the alias name FarmerRegId.
     * @return the value of FarmerRegId
     */
    public BigDecimal getFarmerRegId() {
        return (BigDecimal) getAttributeInternal(FARMERREGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FarmerRegId.
     * @param value value to set the FarmerRegId
     */
    public void setFarmerRegId(BigDecimal value) {
        setAttributeInternal(FARMERREGID, value);
    }

    /**
     * Gets the attribute value for GrantAppMasterId, using the alias name GrantAppMasterId.
     * @return the value of GrantAppMasterId
     */
    public BigDecimal getGrantAppMasterId() {
        return (BigDecimal) getAttributeInternal(GRANTAPPMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantAppMasterId.
     * @param value value to set the GrantAppMasterId
     */
    public void setGrantAppMasterId(BigDecimal value) {
        setAttributeInternal(GRANTAPPMASTERID, value);
    }

    /**
     * Gets the attribute value for Acre, using the alias name Acre.
     * @return the value of Acre
     */
    public BigDecimal getAcre() {
        return (BigDecimal) getAttributeInternal(ACRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Acre.
     * @param value value to set the Acre
     */
    public void setAcre(BigDecimal value) {
        setAttributeInternal(ACRE, value);
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the value of Rate
     */
    public BigDecimal getRate() {
        return (BigDecimal) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(BigDecimal value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for FAcre, using the alias name FAcre.
     * @return the value of FAcre
     */
    public BigDecimal getFAcre() {
        return (BigDecimal) getAttributeInternal(FACRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FAcre.
     * @param value value to set the FAcre
     */
    public void setFAcre(BigDecimal value) {
        setAttributeInternal(FACRE, value);
    }

    /**
     * Gets the attribute value for GrantAmount, using the alias name GrantAmount.
     * @return the value of GrantAmount
     */
    public BigDecimal getGrantAmount() {
        return (BigDecimal) getAttributeInternal(GRANTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantAmount.
     * @param value value to set the GrantAmount
     */
    public void setGrantAmount(BigDecimal value) {
        setAttributeInternal(GRANTAMOUNT, value);
    }

    /**
     * Gets the attribute value for GrantRateId, using the alias name GrantRateId.
     * @return the value of GrantRateId
     */
    public BigDecimal getGrantRateId() {
        return (BigDecimal) getAttributeInternal(GRANTRATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantRateId.
     * @param value value to set the GrantRateId
     */
    public void setGrantRateId(BigDecimal value) {
        setAttributeInternal(GRANTRATEID, value);
    }

    /**
     * Gets the attribute value for FAmount, using the alias name FAmount.
     * @return the value of FAmount
     */
    public BigDecimal getFAmount() {
        return (BigDecimal) getAttributeInternal(FAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FAmount.
     * @param value value to set the FAmount
     */
    public void setFAmount(BigDecimal value) {
        setAttributeInternal(FAMOUNT, value);
    }

    /**
     * Gets the attribute value for GrantStatus, using the alias name GrantStatus.
     * @return the value of GrantStatus
     */
    public String getGrantStatus() {
        return (String) getAttributeInternal(GRANTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantStatus.
     * @param value value to set the GrantStatus
     */
    public void setGrantStatus(String value) {
        setAttributeInternal(GRANTSTATUS, value);
    }

    /**
     * Gets the attribute value for RoNumber, using the alias name RoNumber.
     * @return the value of RoNumber
     */
    public String getRoNumber() {
        return (String) getAttributeInternal(RONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoNumber.
     * @param value value to set the RoNumber
     */
    public void setRoNumber(String value) {
        setAttributeInternal(RONUMBER, value);
    }

    /**
     * Gets the attribute value for RoStatus, using the alias name RoStatus.
     * @return the value of RoStatus
     */
    public String getRoStatus() {
        return (String) getAttributeInternal(ROSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoStatus.
     * @param value value to set the RoStatus
     */
    public void setRoStatus(String value) {
        setAttributeInternal(ROSTATUS, value);
    }

    /**
     * Gets the attribute value for DisburseStatus, using the alias name DisburseStatus.
     * @return the value of DisburseStatus
     */
    public String getDisburseStatus() {
        return (String) getAttributeInternal(DISBURSESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisburseStatus.
     * @param value value to set the DisburseStatus
     */
    public void setDisburseStatus(String value) {
        setAttributeInternal(DISBURSESTATUS, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * @return the associated entity TblFarmerRegImpl.
     */
    public TblFarmerRegImpl getTblFarmerReg() {
        return (TblFarmerRegImpl) getAttributeInternal(TBLFARMERREG);
    }

    /**
     * Sets <code>value</code> as the associated entity TblFarmerRegImpl.
     */
    public void setTblFarmerReg(TblFarmerRegImpl value) {
        setAttributeInternal(TBLFARMERREG, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public TblGrantApprovalMasterImpl getTblGrantApprovalMaster() {
        return (TblGrantApprovalMasterImpl) getAttributeInternal(TBLGRANTAPPROVALMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblGrantApprovalMaster(TblGrantApprovalMasterImpl value) {
        setAttributeInternal(TBLGRANTAPPROVALMASTER, value);
    }

    /**
     * @return the associated entity TblGrantAppMasterImpl.
     */
    public TblGrantAppMasterImpl getTblGrantAppMaster() {
        return (TblGrantAppMasterImpl) getAttributeInternal(TBLGRANTAPPMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity TblGrantAppMasterImpl.
     */
    public void setTblGrantAppMaster(TblGrantAppMasterImpl value) {
        setAttributeInternal(TBLGRANTAPPMASTER, value);
    }


    /**
     * @return the associated entity TblGrantRateImpl.
     */
    public TblGrantRateImpl getTblGrantRate() {
        return (TblGrantRateImpl) getAttributeInternal(TBLGRANTRATE);
    }

    /**
     * Sets <code>value</code> as the associated entity TblGrantRateImpl.
     */
    public void setTblGrantRate(TblGrantRateImpl value) {
        setAttributeInternal(TBLGRANTRATE, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblGrantApprovalDetailD() {
        return (RowIterator) getAttributeInternal(TBLGRANTAPPROVALDETAILD);
    }


    /**
     * @param grantApprovalDetailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal grantApprovalDetailId) {
        return new Key(new Object[] { grantApprovalDetailId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        BigDecimal loginId = null;
         try {
             loginId = new BigDecimal((String) ADFContext.getCurrent().getSessionScope().get("sessUID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

