package model.EO;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 13:03:36 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblGrantGroupMasterImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GrantGroupMasterId,
        GrantGroupMasterPhaseId,
        GrantGroupMasterClusterId,
        GrantGroupMasterNominee,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblGrantGroupDetail,
        TblFarmerReg;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GRANTGROUPMASTERID = AttributesEnum.GrantGroupMasterId.index();
    public static final int GRANTGROUPMASTERPHASEID = AttributesEnum.GrantGroupMasterPhaseId.index();
    public static final int GRANTGROUPMASTERCLUSTERID = AttributesEnum.GrantGroupMasterClusterId.index();
    public static final int GRANTGROUPMASTERNOMINEE = AttributesEnum.GrantGroupMasterNominee.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLGRANTGROUPDETAIL = AttributesEnum.TblGrantGroupDetail.index();
    public static final int TBLFARMERREG = AttributesEnum.TblFarmerReg.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblGrantGroupMasterImpl() {
    }

    /**
     * Gets the attribute value for GrantGroupMasterId, using the alias name GrantGroupMasterId.
     * @return the value of GrantGroupMasterId
     */
    public Number getGrantGroupMasterId() {
        return (Number) getAttributeInternal(GRANTGROUPMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantGroupMasterId.
     * @param value value to set the GrantGroupMasterId
     */
    public void setGrantGroupMasterId(Number value) {
        setAttributeInternal(GRANTGROUPMASTERID, value);
    }

    /**
     * Gets the attribute value for GrantGroupMasterPhaseId, using the alias name GrantGroupMasterPhaseId.
     * @return the value of GrantGroupMasterPhaseId
     */
    public Number getGrantGroupMasterPhaseId() {
        return (Number) getAttributeInternal(GRANTGROUPMASTERPHASEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantGroupMasterPhaseId.
     * @param value value to set the GrantGroupMasterPhaseId
     */
    public void setGrantGroupMasterPhaseId(Number value) {
        setAttributeInternal(GRANTGROUPMASTERPHASEID, value);
    }

    /**
     * Gets the attribute value for GrantGroupMasterClusterId, using the alias name GrantGroupMasterClusterId.
     * @return the value of GrantGroupMasterClusterId
     */
    public Number getGrantGroupMasterClusterId() {
        return (Number) getAttributeInternal(GRANTGROUPMASTERCLUSTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantGroupMasterClusterId.
     * @param value value to set the GrantGroupMasterClusterId
     */
    public void setGrantGroupMasterClusterId(Number value) {
        setAttributeInternal(GRANTGROUPMASTERCLUSTERID, value);
    }

    /**
     * Gets the attribute value for GrantGroupMasterNominee, using the alias name GrantGroupMasterNominee.
     * @return the value of GrantGroupMasterNominee
     */
    public Number getGrantGroupMasterNominee() {
        return (Number) getAttributeInternal(GRANTGROUPMASTERNOMINEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantGroupMasterNominee.
     * @param value value to set the GrantGroupMasterNominee
     */
    public void setGrantGroupMasterNominee(Number value) {
        setAttributeInternal(GRANTGROUPMASTERNOMINEE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblGrantGroupDetail() {
        return (RowIterator) getAttributeInternal(TBLGRANTGROUPDETAIL);
    }

    /**
     * @return the associated entity TblFarmerRegImpl.
     */
    public TblFarmerRegImpl getTblFarmerReg() {
        return (TblFarmerRegImpl) getAttributeInternal(TBLFARMERREG);
    }

    /**
     * Sets <code>value</code> as the associated entity TblFarmerRegImpl.
     */
    public void setTblFarmerReg(TblFarmerRegImpl value) {
        setAttributeInternal(TBLFARMERREG, value);
    }

    /**
     * @param grantGroupMasterId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number grantGroupMasterId) {
        return new Key(new Object[] { grantGroupMasterId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblGrantGroupMaster");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

