package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 12:38:17 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblGrantApprovalDetailDImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GrantApprovalDetailDId,
        GrantApprovalDetailId,
        ItemL4Id,
        Rate,
        Amount,
        Qty,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblGrantApprovalDetail;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GRANTAPPROVALDETAILDID = AttributesEnum.GrantApprovalDetailDId.index();
    public static final int GRANTAPPROVALDETAILID = AttributesEnum.GrantApprovalDetailId.index();
    public static final int ITEML4ID = AttributesEnum.ItemL4Id.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLGRANTAPPROVALDETAIL = AttributesEnum.TblGrantApprovalDetail.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblGrantApprovalDetailDImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblGrantApprovalDetailD");
    }


    /**
     * Gets the attribute value for GrantApprovalDetailDId, using the alias name GrantApprovalDetailDId.
     * @return the value of GrantApprovalDetailDId
     */
    public Number getGrantApprovalDetailDId() {
        return (Number) getAttributeInternal(GRANTAPPROVALDETAILDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantApprovalDetailDId.
     * @param value value to set the GrantApprovalDetailDId
     */
    public void setGrantApprovalDetailDId(Number value) {
        setAttributeInternal(GRANTAPPROVALDETAILDID, value);
    }

    /**
     * Gets the attribute value for GrantApprovalDetailId, using the alias name GrantApprovalDetailId.
     * @return the value of GrantApprovalDetailId
     */
    public Number getGrantApprovalDetailId() {
        return (Number) getAttributeInternal(GRANTAPPROVALDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantApprovalDetailId.
     * @param value value to set the GrantApprovalDetailId
     */
    public void setGrantApprovalDetailId(Number value) {
        setAttributeInternal(GRANTAPPROVALDETAILID, value);
    }

    /**
     * Gets the attribute value for ItemL4Id, using the alias name ItemL4Id.
     * @return the value of ItemL4Id
     */
    public Number getItemL4Id() {
        return (Number) getAttributeInternal(ITEML4ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemL4Id.
     * @param value value to set the ItemL4Id
     */
    public void setItemL4Id(Number value) {
        setAttributeInternal(ITEML4ID, value);
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the value of Rate
     */
    public Number getRate() {
        return (Number) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the value of Qty
     */
    public Number getQty() {
        return (Number) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity TblGrantApprovalDetailImpl.
     */
    public TblGrantApprovalDetailImpl getTblGrantApprovalDetail() {
        return (TblGrantApprovalDetailImpl) getAttributeInternal(TBLGRANTAPPROVALDETAIL);
    }

    /**
     * Sets <code>value</code> as the associated entity TblGrantApprovalDetailImpl.
     */
    public void setTblGrantApprovalDetail(TblGrantApprovalDetailImpl value) {
        setAttributeInternal(TBLGRANTAPPROVALDETAIL, value);
    }


    /**
     * @param grantApprovalDetailDId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number grantApprovalDetailDId) {
        return new Key(new Object[] { grantApprovalDetailDId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

