package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 30 12:57:05 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblIntlDelegImportOthImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IntlDelegImportOthId,
        IntlDelegAppMId,
        LibrCountryId,
        ProdImport,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        TblIntlDelegAppM;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INTLDELEGIMPORTOTHID = AttributesEnum.IntlDelegImportOthId.index();
    public static final int INTLDELEGAPPMID = AttributesEnum.IntlDelegAppMId.index();
    public static final int LIBRCOUNTRYID = AttributesEnum.LibrCountryId.index();
    public static final int PRODIMPORT = AttributesEnum.ProdImport.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TBLINTLDELEGAPPM = AttributesEnum.TblIntlDelegAppM.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblIntlDelegImportOthImpl() {
    }

    /**
     * Gets the attribute value for IntlDelegImportOthId, using the alias name IntlDelegImportOthId.
     * @return the value of IntlDelegImportOthId
     */
    public Number getIntlDelegImportOthId() {
        return (Number) getAttributeInternal(INTLDELEGIMPORTOTHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntlDelegImportOthId.
     * @param value value to set the IntlDelegImportOthId
     */
    public void setIntlDelegImportOthId(Number value) {
        setAttributeInternal(INTLDELEGIMPORTOTHID, value);
    }

    /**
     * Gets the attribute value for IntlDelegAppMId, using the alias name IntlDelegAppMId.
     * @return the value of IntlDelegAppMId
     */
    public Number getIntlDelegAppMId() {
        return (Number) getAttributeInternal(INTLDELEGAPPMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntlDelegAppMId.
     * @param value value to set the IntlDelegAppMId
     */
    public void setIntlDelegAppMId(Number value) {
        setAttributeInternal(INTLDELEGAPPMID, value);
    }

    /**
     * Gets the attribute value for LibrCountryId, using the alias name LibrCountryId.
     * @return the value of LibrCountryId
     */
    public Number getLibrCountryId() {
        return (Number) getAttributeInternal(LIBRCOUNTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LibrCountryId.
     * @param value value to set the LibrCountryId
     */
    public void setLibrCountryId(Number value) {
        setAttributeInternal(LIBRCOUNTRYID, value);
    }

    /**
     * Gets the attribute value for ProdImport, using the alias name ProdImport.
     * @return the value of ProdImport
     */
    public String getProdImport() {
        return (String) getAttributeInternal(PRODIMPORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdImport.
     * @param value value to set the ProdImport
     */
    public void setProdImport(String value) {
        setAttributeInternal(PRODIMPORT, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @return the associated entity TblIntlDelegAppMImpl.
     */
    public TblIntlDelegAppMImpl getTblIntlDelegAppM() {
        return (TblIntlDelegAppMImpl) getAttributeInternal(TBLINTLDELEGAPPM);
    }

    /**
     * Sets <code>value</code> as the associated entity TblIntlDelegAppMImpl.
     */
    public void setTblIntlDelegAppM(TblIntlDelegAppMImpl value) {
        setAttributeInternal(TBLINTLDELEGAPPM, value);
    }

    /**
     * @param intlDelegImportOthId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number intlDelegImportOthId) {
        return new Key(new Object[] { intlDelegImportOthId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblIntlDelegImportOth");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                 try {
                     loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
                 } catch(Exception ex) {
                     ex.printStackTrace();
                 }
                 
                 if (operation == DML_INSERT) {
                     setCreatedBy(loginId);
                     setUpdatedBy(loginId);
                     } else if(operation == DML_UPDATE) {
                     setUpdatedBy(loginId);
                 }
        super.doDML(operation, e);
    }
}

