package model.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 27 16:13:29 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblMonParamImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MonParamId,
        OutputIndId,
        Name,
        Perc,
        Ast,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblOutputInd;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MONPARAMID = AttributesEnum.MonParamId.index();
    public static final int OUTPUTINDID = AttributesEnum.OutputIndId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PERC = AttributesEnum.Perc.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLOUTPUTIND = AttributesEnum.TblOutputInd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblMonParamImpl() {
    }

    /**
     * Gets the attribute value for MonParamId, using the alias name MonParamId.
     * @return the value of MonParamId
     */
    public BigDecimal getMonParamId() {
        return (BigDecimal) getAttributeInternal(MONPARAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MonParamId.
     * @param value value to set the MonParamId
     */
    public void setMonParamId(BigDecimal value) {
        setAttributeInternal(MONPARAMID, value);
    }

    /**
     * Gets the attribute value for OutputIndId, using the alias name OutputIndId.
     * @return the value of OutputIndId
     */
    public BigDecimal getOutputIndId() {
        return (BigDecimal) getAttributeInternal(OUTPUTINDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OutputIndId.
     * @param value value to set the OutputIndId
     */
    public void setOutputIndId(BigDecimal value) {
        setAttributeInternal(OUTPUTINDID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Perc, using the alias name Perc.
     * @return the value of Perc
     */
    public Integer getPerc() {
        return (Integer) getAttributeInternal(PERC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Perc.
     * @param value value to set the Perc
     */
    public void setPerc(Integer value) {
        setAttributeInternal(PERC, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity TblOutputIndImpl.
     */
    public TblOutputIndImpl getTblOutputInd() {
        return (TblOutputIndImpl) getAttributeInternal(TBLOUTPUTIND);
    }

    /**
     * Sets <code>value</code> as the associated entity TblOutputIndImpl.
     */
    public void setTblOutputInd(TblOutputIndImpl value) {
        setAttributeInternal(TBLOUTPUTIND, value);
    }

    /**
     * @param monParamId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal monParamId) {
        return new Key(new Object[] { monParamId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblMonParam");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        BigDecimal loginId = null;
        try {
            loginId = new BigDecimal((String) ADFContext.getCurrent().getSessionScope().get("sessUID"));
        } catch(Exception ex) {
            ex.printStackTrace();
        }
        
        if (operation == DML_INSERT) {
            setCreatedBy(loginId);
            setUpdatedBy(loginId);
        } else {
            setUpdatedBy(loginId);
        }
        super.doDML(operation, e);
    }
}

