package model.EO;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 13:09:00 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblRoleDetailReportsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RoleDetailReportsId,
        RoleMasterId,
        ReportsId,
        RView,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblReports,
        TblRoleMaster;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROLEDETAILREPORTSID = AttributesEnum.RoleDetailReportsId.index();
    public static final int ROLEMASTERID = AttributesEnum.RoleMasterId.index();
    public static final int REPORTSID = AttributesEnum.ReportsId.index();
    public static final int RVIEW = AttributesEnum.RView.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLREPORTS = AttributesEnum.TblReports.index();
    public static final int TBLROLEMASTER = AttributesEnum.TblRoleMaster.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblRoleDetailReportsImpl() {
    }

    /**
     * Gets the attribute value for RoleDetailReportsId, using the alias name RoleDetailReportsId.
     * @return the value of RoleDetailReportsId
     */
    public Number getRoleDetailReportsId() {
        return (Number) getAttributeInternal(ROLEDETAILREPORTSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoleDetailReportsId.
     * @param value value to set the RoleDetailReportsId
     */
    public void setRoleDetailReportsId(Number value) {
        setAttributeInternal(ROLEDETAILREPORTSID, value);
    }

    /**
     * Gets the attribute value for RoleMasterId, using the alias name RoleMasterId.
     * @return the value of RoleMasterId
     */
    public Number getRoleMasterId() {
        return (Number) getAttributeInternal(ROLEMASTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoleMasterId.
     * @param value value to set the RoleMasterId
     */
    public void setRoleMasterId(Number value) {
        setAttributeInternal(ROLEMASTERID, value);
    }

    /**
     * Gets the attribute value for ReportsId, using the alias name ReportsId.
     * @return the value of ReportsId
     */
    public Number getReportsId() {
        return (Number) getAttributeInternal(REPORTSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReportsId.
     * @param value value to set the ReportsId
     */
    public void setReportsId(Number value) {
        setAttributeInternal(REPORTSID, value);
    }

    /**
     * Gets the attribute value for RView, using the alias name RView.
     * @return the value of RView
     */
    public String getRView() {
        return (String) getAttributeInternal(RVIEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for RView.
     * @param value value to set the RView
     */
    public void setRView(String value) {
        setAttributeInternal(RVIEW, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblReports() {
        return (EntityImpl) getAttributeInternal(TBLREPORTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblReports(EntityImpl value) {
        setAttributeInternal(TBLREPORTS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTblRoleMaster() {
        return (EntityImpl) getAttributeInternal(TBLROLEMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTblRoleMaster(EntityImpl value) {
        setAttributeInternal(TBLROLEMASTER, value);
    }

    /**
     * @param roleDetailReportsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number roleDetailReportsId) {
        return new Key(new Object[] { roleDetailReportsId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.TblRoleDetailReports");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
         try {
             loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {
             setCreatedBy(loginId);
             setUpdatedBy(loginId);
             } else if(operation == DML_UPDATE) {
             setUpdatedBy(loginId);
         }
        super.doDML(operation, e);
    }
}

